#!/bin/sh
#=============================================================================
#
#             --- CAEN SpA - Computing Systems Division ---
#
#  Library installation script for x86_64 systems.
#
#=============================================================================

if [ ! -f /usr/lib/libCAENComm.so ] 
then
    echo >&2 "*******************************************************************"
    echo >&2 "* ERROR                                                           *"
    echo >&2 "* This library requires the CAENComm library.                     *"
    echo >&2 "* Please download it from the following link:                     *"
    echo >&2 "*                                                                 *"
    echo >&2 "* https://www.caen.it/download/                                   *"
    echo >&2 "*                                                                 *"
    echo >&2 "* Install it and run try again.                                   *"
    echo >&2 "*******************************************************************"
    exit 1
fi

search_dir=./x64

for file in "$search_dir"/*
do
    install $file /usr/lib/
    filename="$(basename -- $file)"
    ln -sf /usr/lib/$filename /usr/lib/libCAEN_PLU.so
done

/sbin/ldconfig

for file in ../include/*
do
    install -m 644 $file /usr/include/
done

# Add rule to allow access as non root
echo "SUBSYSTEM==\"usb\", DRIVER==\"usb\", ATTR{idVendor}==\"21e1\", ATTR{idProduct}==\"000a\", MODE=\"0666\"" >  /etc/udev/rules.d/10-CAEN-V2495.rules
udevadm control --reload-rules && udevadm trigger
echo "V2495 correctly installed!"
